import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "./Utama/Navbar"
import styles from "./style"
import Footer from "./Utama/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar className="z-[99]"/>

        <div className={`w-full`}>
          <div className={`${styles.padding} `}>
          </div>
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}

